name: progetto-test
recipe: lamp
config:
  php: '8.1'
  webroot: backend
  database: mysql:5.7
  xdebug: false

services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install -y git
    composer:
      phpunit/phpunit: '*'

  database:
    portforward: 3306
    creds:
      user: admin
      password: sviluppo
      database: progetto
      
  pma:
    type: phpmyadmin
    hosts:
      - database

tooling:
  composer:
    service: appserver
    cmd: composer
  
  php:
    service: appserver
    cmd: php

  mysql:
    service: database
    cmd: mysql
  
  phpmyadmin:
    service: pma
    cmd: lando-pma

proxy:
  appserver:
    - progetto-test.lndo.site
  pma:
    - pma-progetto-test.lndo.site