name: orders-api
recipe: lamp
config:
  php: '8.1'
  webroot: backend
  database: mysql:5.7
  xdebug: false

services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install -y git curl
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
    composer:
      phpunit/phpunit: '*'
    build:
      - npm install

  database:
    portforward: 3306
    creds:
      user: admin
      password: sviluppo
      database: progetto
      
  pma:
    type: phpmyadmin
    hosts:
      - database

tooling:
  composer:
    service: appserver
    cmd: composer
  
  php:
    service: appserver
    cmd: php

  mysql:
    service: database
    cmd: mysql
  
  phpmyadmin:
    service: pma
    cmd: lando-pma
    
  npm:
    service: appserver
    cmd: npm
    
  'npm:i':
    service: appserver
    cmd: npm i
    
  'npm:build':
    service: appserver
    cmd: npm run build
    
  'npm:dev':
    service: appserver
    cmd: npm run dev
    
  node:
    service: appserver
    cmd: node

proxy:
  appserver:
    - orders-api.lndo.site
  pma:
    - pma-orders-api.lndo.site